### ISSUE TITLE
Not sure where to put this

### ISSUE THREAD

**Issue by Jesse-Lucas1996** [swichers/dndbeyond-screen#94]
Can't mouse wheel scroll on the dnd beyond website when death saving throw menu

**Comment by swichers** [comment]
Hi, this project is unaffiliated with the official D&D Beyond website. This is a third party DM screen I put together to track player health and other stats. I believe the D&D Beyond website forums have a bug reporting area. You might try there.

https://www.dndbeyond.com/forums/d-d-beyond-general/bugs-support
